apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
  labels:
    app: go-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: seu-usuario-dockerhub/go-microservice:latest # Substitua pelo seu nome de usuário!
        ports:
        - containerPort: 8080
        # Configurações de probes para alta disponibilidade
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10