name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Install and test
        run: |
          go mod download
          go test ./...

      - name: Login on Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/go-microservice:latest
          file: ./Dockerfile
      
      # Commented so run manually
      # - name: Configure kubeconfig
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # - name: Deploy on Kubernetes
      #   run: |
      #     kubectl apply -f kubernetes/
      #     kubectl rollout status deployment/go-api-deployment